    const COUNTRY_FACTS = {
        "afghanistan": "Did you know that in Afghanistan, the capital city is Kabul and it has a population of 37,172,386 people?",
        "albania": "Did you know that in Albania, the capital city is Tirana and it has a population of 2,866,376 people?",
        "algeria": "Did you know that in Algeria, the capital city is Alger and it has a population of 42,228,429 people?",
        "andorra": "Did you know that in Andorra, the capital city is Andorra la Vella and it has a population of 77,006 people?",
        "angola": "Did you know that in Angola, the capital city is Luanda and it has a population of 30,809,762 people?",
        "antigua": "Did you know that in Antigua and Barbuda, the capital city is Saint John\'s and it has a population of 96,286 people?",
        "argentina": "Did you know that in Argentina, the capital city is Buenos Aires and it has a population of 44,494,502 people?",
        "armenia": "Did you know that in Armenia, the capital city is Yerevan and it has a population of 2,951,776 people?",
        "australia": "Did you know that in Australia, the capital city is Canberra and it has a population of 24,982,688 people?",
        "austria": "Did you know that in Austria, the capital city is Wien and it has a population of 8,840,521 people?",
        "azerbaijan": "Did you know that in Azerbaijan, the capital city is Baku and it has a population of 9,939,800 people?",
        "bahamas": "Did you know that in Bahamas, the capital city is Nassau and it has a population of 385,640 people?",
        "bahrain": "Did you know that in Bahrain, the capital city is al-Manama and it has a population of 1,569,439 people?",
        "bangladesh": "Did you know that in Bangladesh, the capital city is Dhaka and it has a population of 161,356,039 people?",
        "barbados": "Did you know that in Barbados, the capital city is Bridgetown and it has a population of 286,641 people?",
        "belarus": "Did you know that in Belarus, the capital city is Minsk and it has a population of 9,483,499 people?",
        "belgium": "Did you know that in Belgium, the capital city is Bruxelles [Brussel] and it has a population of 11,433,256 people?",
        "belize": "Did you know that in Belize, the capital city is Belmopan and it has a population of 383,071 people?",
        "benin": "Did you know that in Benin, the capital city is Porto-Novo and it has a population of 11,485,048 people?",
        "bhutan": "Did you know that in Bhutan, the capital city is Thimphu and it has a population of 754,394 people?",
        "bolivia": "Did you know that in Bolivia, the capital city is La Paz and it has a population of 11,353,142 people?",
        "bosnia": "Did you know that in Bosnia and Herzegovina, the capital city is Sarajevo and it has a population of 3,323,929 people?",
        "botswana": "Did you know that in Botswana, the capital city is Gaborone and it has a population of 2,254,126 people?",
        "brazil": "Did you know that in Brazil, the capital city is Brasília and it has a population of 209,469,333 people?",
        "brunei": "Did you know that in Brunei, the capital city is Bandar Seri Begawan and it has a population of 428,962 people?",
        "bulgaria": "Did you know that in Bulgaria, the capital city is Sofia and it has a population of 7,025,037 people?",
        "burkina": "Did you know that in Burkina Faso, the capital city is Ouagadougou and it has a population of 19,751,535 people?",
        "burundi": "Did you know that in Burundi, the capital city is Bujumbura and it has a population of 11,175,378 people?",
        "cabo": "Did you know that Cabo Verde is fascinating? It has a population of 555,987 people.",
        "cambodia": "Did you know that in Cambodia, the capital city is Phnom Penh and it has a population of 16,249,798 people?",
        "cameroon": "Did you know that in Cameroon, the capital city is Yaounde and it has a population of 25,216,237 people?",
        "canada": "Did you know that in Canada, the capital city is Ottawa and it has a population of 37,057,765 people?",
        "central": "Did you know that in Central African Republic, the capital city is Bangui and it has a population of 4,666,377 people?",
        "chad": "Did you know that in Chad, the capital city is N\'Djamena and it has a population of 15,477,751 people?",
        "chile": "Did you know that in Chile, the capital city is Santiago de Chile and it has a population of 18,729,160 people?",
        "china": "Did you know that in China, the capital city is Peking and it has a population of 1,392,730,000 people?",
        "colombia": "Did you know that in Colombia, the capital city is Bogota and it has a population of 49,648,685 people?",
        "comoros": "Did you know that in Comoros, the capital city is Moroni and it has a population of 832,322 people?",
        "congo": "Did you know that in Congo, the capital city is Brazzaville and it has a population of 5,244,363 people?",
        "costa": "Did you know that in Costa Rica, the capital city is San José and it has a population of 4,999,441 people?",
        "croatia": "Did you know that in Croatia, the capital city is Zagreb and it has a population of 4,087,843 people?",
        "cuba": "Did you know that in Cuba, the capital city is La Habana and it has a population of 11,338,138 people?",
        "cyprus": "Did you know that in Cyprus, the capital city is Nicosia and it has a population of 1,189,265 people?",
        "czech": "Did you know that in Czech Republic, the capital city is Praha and it has a population of 10,629,928 people?",
        "denmark": "Did you know that in Denmark, the capital city is Copenhagen and it has a population of 5,793,636 people?",
        "djibouti": "Did you know that in Djibouti, the capital city is Djibouti and it has a population of 958,920 people?",
        "dominica": "Did you know that in Dominica, the capital city is Roseau and it has a population of 71,625 people?",
        "dominican": "Did you know that in Dominican Republic, the capital city is Santo Domingo de Guzm and it has a population of 10,627,165 people?",
        "ecuador": "Did you know that in Ecuador, the capital city is Quito and it has a population of 17,084,357 people?",
        "egypt": "Did you know that in Egypt, the capital city is Cairo and it has a population of 98,423,595 people?",
        "el": "Did you know that in El Salvador, the capital city is San Salvador and it has a population of 6,420,744 people?",
        "equatorial": "Did you know that in Equatorial Guinea, the capital city is Malabo and it has a population of 1,308,974 people?",
        "eritrea": "Did you know that in Eritrea, the capital city is Asmara and it has a population of 6,213,972 people?",
        "estonia": "Did you know that in Estonia, the capital city is Tallinn and it has a population of 1,321,977 people?",
        "eswatini": "Did you know that in Eswatini, the capital city is Mbabane and it has a population of 1,136,191 people?",
        "ethiopia": "Did you know that in Ethiopia, the capital city is Addis Abeba and it has a population of 109,224,559 people?",
        "fiji": "Did you know? Fiji is full of hidden gems waiting to be explored.",
        "finland": "Did you know that in Finland, the capital city is Helsinki [Helsingfors] and it has a population of 5,515,525 people?",
        "france": "Did you know that in France, the capital city is Paris and it has a population of 66,977,107 people?",
        "gabon": "Did you know that in Gabon, the capital city is Libreville and it has a population of 2,119,275 people?",
        "gambia": "Did you know that in Gambia, the capital city is Banjul and it has a population of 2,280,102 people?",
        "georgia": "Did you know that in Georgia, the capital city is Tbilisi and it has a population of 3,726,549 people?",
        "germany": "Did you know that in Germany, the capital city is Berlin and it has a population of 82,905,782 people?",
        "ghana": "Did you know that in Ghana, the capital city is Accra and it has a population of 29,767,108 people?",
        "greece": "Did you know that in Greece, the capital city is Athenai and it has a population of 10,731,726 people?",
        "grenada": "Did you know that in Grenada, the capital city is Saint George\'s and it has a population of 111,454 people?",
        "guatemala": "Did you know that in Guatemala, the capital city is Ciudad de Guatemala and it has a population of 17,247,807 people?",
        "guinea": "Did you know that in Guinea, the capital city is Conakry and it has a population of 12,414,318 people?",
        "guinea-bissau": "Did you know that in Guinea-Bissau, the capital city is Bissau and it has a population of 1,874,309 people?",
        "guyana": "Did you know that in Guyana, the capital city is Georgetown and it has a population of 779,004 people?",
        "haiti": "Did you know that in Haiti, the capital city is Port-au-Prince and it has a population of 11,123,176 people?",
        "honduras": "Did you know that in Honduras, the capital city is Tegucigalpa and it has a population of 9,587,522 people?",
        "hungary": "Did you know that in Hungary, the capital city is Budapest and it has a population of 9,775,564 people?",
        "iceland": "Did you know that in Iceland, the capital city is Reykjavík and it has a population of 352,721 people?",
        "india": "Did you know that in India, the capital city is New Delhi and it has a population of 1,352,617,328 people?",
        "indonesia": "Did you know that in Indonesia, the capital city is Jakarta and it has a population of 267,663,435 people?",
        "iran": "Did you know that in Iran, the capital city is Tehran and it has a population of 81,800,269 people?",
        "iraq": "Did you know that in Iraq, the capital city is Baghdad and it has a population of 38,433,600 people?",
        "ireland": "Did you know that in Ireland, the capital city is Dublin and it has a population of 4,867,309 people?",
        "israel": "Did you know that in Israel, the capital city is Jerusalem and it has a population of 8,882,800 people?",
        "italy": "Did you know that in Italy, the capital city is Roma and it has a population of 60,421,760 people?",
        "jamaica": "Did you know that in Jamaica, the capital city is Kingston and it has a population of 2,934,855 people?",
        "japan": "Did you know that in Japan, the capital city is Tokyo and it has a population of 126,529,100 people?",
        "jordan": "Did you know that in Jordan, the capital city is Amman and it has a population of 9,956,011 people?",
        "kazakhstan": "Did you know that in Kazakhstan, the capital city is Astana and it has a population of 18,272,430 people?",
        "kenya": "Did you know that in Kenya, the capital city is Nairobi and it has a population of 51,393,010 people?",
        "kiribati": "Did you know that in Kiribati, the capital city is Bairiki and it has a population of 115,847 people?",
        "korea,": "Did you know? Korea, North is full of hidden gems waiting to be explored.",
        "korea,": "Did you know that in Korea, South, the capital city is Seoul and it has a population of 51,606,633 people?",
        "kosovo": "Did you know? Kosovo is full of hidden gems waiting to be explored.",
        "kuwait": "Did you know that in Kuwait, the capital city is Kuwait and it has a population of 4,137,309 people?",
        "kyrgyzstan": "Did you know that in Kyrgyzstan, the capital city is Bishkek and it has a population of 6,322,800 people?",
        "laos": "Did you know that in Laos, the capital city is Vientiane and it has a population of 7,061,507 people?",
        "latvia": "Did you know that in Latvia, the capital city is Riga and it has a population of 1,927,174 people?",
        "lebanon": "Did you know that in Lebanon, the capital city is Beirut and it has a population of 6,848,925 people?",
        "lesotho": "Did you know that in Lesotho, the capital city is Maseru and it has a population of 2,108,132 people?",
        "liberia": "Did you know that in Liberia, the capital city is Monrovia and it has a population of 4,818,977 people?",
        "libya": "Did you know that in Libya, the capital city is Tripoli and it has a population of 6,678,567 people?",
        "liechtenstein": "Did you know that in Liechtenstein, the capital city is Vaduz and it has a population of 37,910 people?",
        "lithuania": "Did you know that in Lithuania, the capital city is Vilnius and it has a population of 2,801,543 people?",
        "luxembourg": "Did you know that in Luxembourg, the capital city is Luxembourg [Luxemburg/L and it has a population of 607,950 people?",
        "madagascar": "Did you know that in Madagascar, the capital city is Antananarivo and it has a population of 26,262,368 people?",
        "malawi": "Did you know that in Malawi, the capital city is Lilongwe and it has a population of 18,143,315 people?",
        "malaysia": "Did you know that in Malaysia, the capital city is Kuala Lumpur and it has a population of 31,528,585 people?",
        "maldives": "Did you know that in Maldives, the capital city is Male and it has a population of 515,696 people?",
        "mali": "Did you know that in Mali, the capital city is Bamako and it has a population of 19,077,690 people?",
        "malta": "Did you know that in Malta, the capital city is Valletta and it has a population of 484,630 people?",
        "marshall": "Did you know that in Marshall Islands, the capital city is Dalap-Uliga-Darrit and it has a population of 58,413 people?",
        "mauritania": "Did you know that in Mauritania, the capital city is Nouakchott and it has a population of 4,403,319 people?",
        "mauritius": "Did you know that in Mauritius, the capital city is Port-Louis and it has a population of 1,265,303 people?",
        "mexico": "Did you know that in Mexico, the capital city is Ciudad de M and it has a population of 126,190,788 people?",
        "micronesia": "Did you know? Micronesia is full of hidden gems waiting to be explored.",
        "moldova": "Did you know that in Moldova, the capital city is Chisinau and it has a population of 2,706,049 people?",
        "monaco": "Did you know that in Monaco, the capital city is Monaco-Ville and it has a population of 38,682 people?",
        "mongolia": "Did you know that in Mongolia, the capital city is Ulan Bator and it has a population of 3,170,208 people?",
        "montenegro": "Did you know that in Montenegro, the capital city is Podgorica and it has a population of 631,219 people?",
        "morocco": "Did you know that in Morocco, the capital city is Rabat and it has a population of 36,029,138 people?",
        "mozambique": "Did you know that in Mozambique, the capital city is Maputo and it has a population of 29,495,962 people?",
        "myanmar": "Did you know that in Myanmar, the capital city is Rangoon (Yangon) and it has a population of 53,708,395 people?",
        "namibia": "Did you know that in Namibia, the capital city is Windhoek and it has a population of 2,448,255 people?",
        "nauru": "Did you know that in Nauru, the capital city is Yaren and it has a population of 12,704 people?",
        "nepal": "Did you know that in Nepal, the capital city is Kathmandu and it has a population of 28,087,871 people?",
        "netherlands": "Did you know that in Netherlands, the capital city is Amsterdam and it has a population of 17,231,624 people?",
        "new": "Did you know that in New Zealand, the capital city is Wellington and it has a population of 4,841,000 people?",
        "nicaragua": "Did you know that in Nicaragua, the capital city is Managua and it has a population of 6,465,513 people?",
        "niger": "Did you know that in Niger, the capital city is Niamey and it has a population of 22,442,948 people?",
        "nigeria": "Did you know that in Nigeria, the capital city is Abuja and it has a population of 195,874,740 people?",
        "north": "Did you know that in North Macedonia, the capital city is Skopje and it has a population of 2,084,367 people?",
        "norway": "Did you know that in Norway, the capital city is Oslo and it has a population of 5,311,916 people?",
        "oman": "Did you know that in Oman, the capital city is Masqat and it has a population of 4,829,483 people?",
        "pakistan": "Did you know that in Pakistan, the capital city is Islamabad and it has a population of 212,215,030 people?",
        "palau": "Did you know that in Palau, the capital city is Koror and it has a population of 17,907 people?",
        "palestine": "Did you know that in Palestine, the capital city is Gaza and it has a population of 4,569,087 people?",
        "panama": "Did you know that in Panama, the capital city is Ciudad de Panamá and it has a population of 4,176,873 people?",
        "papua": "Did you know that in Papua New Guinea, the capital city is Port Moresby and it has a population of 8,606,316 people?",
        "paraguay": "Did you know that in Paraguay, the capital city is Asunción and it has a population of 6,956,071 people?",
        "peru": "Did you know that in Peru, the capital city is Lima and it has a population of 31,989,256 people?",
        "philippines": "Did you know that in Philippines, the capital city is Manila and it has a population of 106,651,922 people?",
        "poland": "Did you know that in Poland, the capital city is Warszawa and it has a population of 37,974,750 people?",
        "portugal": "Did you know that in Portugal, the capital city is Lisboa and it has a population of 10,283,822 people?",
        "qatar": "Did you know that in Qatar, the capital city is Doha and it has a population of 2,781,677 people?",
        "romania": "Did you know that in Romania, the capital city is Bucuresti and it has a population of 19,466,145 people?",
        "russia": "Did you know? Russia is full of hidden gems waiting to be explored.",
        "rwanda": "Did you know that in Rwanda, the capital city is Kigali and it has a population of 12,301,939 people?",
        "saint": "Did you know that in Saint Kitts and Nevis, the capital city is Basseterre and it has a population of 52,441 people?",
        "saint": "Did you know that in Saint Lucia, the capital city is Castries and it has a population of 181,889 people?",
        "saint": "Did you know? Saint Vincent is full of hidden gems waiting to be explored.",
        "samoa": "Did you know that in Samoa, the capital city is Apia and it has a population of 196,130 people?",
        "san": "Did you know that in San Marino, the capital city is San Marino and it has a population of 33,785 people?",
        "sao": "Did you know that in Sao Tome and Principe, the capital city is São Tomé and it has a population of 211,028 people?",
        "saudi": "Did you know that in Saudi Arabia, the capital city is Riyadh and it has a population of 33,699,947 people?",
        "senegal": "Did you know that in Senegal, the capital city is Dakar and it has a population of 15,854,360 people?",
        "serbia": "Did you know that in Serbia, the capital city is Belgrade and it has a population of 6,963,764 people?",
        "seychelles": "Did you know that in Seychelles, the capital city is Victoria and it has a population of 96,762 people?",
        "sierra": "Did you know that in Sierra Leone, the capital city is Freetown and it has a population of 7,650,154 people?",
        "singapore": "Did you know that in Singapore, the capital city is Singapore and it has a population of 5,638,676 people?",
        "slovakia": "Did you know that in Slovakia, the capital city is Bratislava and it has a population of 5,446,771 people?",
        "slovenia": "Did you know that in Slovenia, the capital city is Ljubljana and it has a population of 2,073,894 people?",
        "solomon": "Did you know that in Solomon Islands, the capital city is Honiara and it has a population of 652,858 people?",
        "somalia": "Did you know that in Somalia, the capital city is Mogadishu and it has a population of 15,008,154 people?",
        "south": "Did you know that in South Africa, the capital city is Pretoria and it has a population of 57,779,622 people?",
        "south": "Did you know that in South Sudan, the capital city is Juba and it has a population of 10,975,920 people?",
        "spain": "Did you know that in Spain, the capital city is Madrid and it has a population of 46,796,540 people?",
        "sri": "Did you know that in Sri Lanka, the capital city is Colombo, Sri Jayawardenepura Kotte and it has a population of 21,670,000 people?",
        "sudan": "Did you know that in Sudan, the capital city is Khartum and it has a population of 41,801,533 people?",
        "suriname": "Did you know that in Suriname, the capital city is Paramaribo and it has a population of 575,991 people?",
        "sweden": "Did you know that in Sweden, the capital city is Stockholm and it has a population of 10,175,214 people?",
        "switzerland": "Did you know that in Switzerland, the capital city is Bern and it has a population of 8,513,227 people?",
        "syria": "Did you know that in Syria, the capital city is Damascus and it has a population of 16,906,283 people?",
        "taiwan": "Did you know? Taiwan is full of hidden gems waiting to be explored.",
        "tajikistan": "Did you know that in Tajikistan, the capital city is Dushanbe and it has a population of 9,100,837 people?",
        "tanzania": "Did you know that in Tanzania, the capital city is Dodoma and it has a population of 56,318,348 people?",
        "thailand": "Did you know that in Thailand, the capital city is Bangkok and it has a population of 69,428,524 people?",
        "timor-leste": "Did you know? Timor-Leste is full of hidden gems waiting to be explored.",
        "togo": "Did you know that in Togo, the capital city is Lomé and it has a population of 7,889,094 people?",
        "tonga": "Did you know that in Tonga, the capital city is Nuku\'alofa and it has a population of 103,197 people?",
        "trinidad": "Did you know that in Trinidad and Tobago, the capital city is Port-of-Spain and it has a population of 1,389,858 people?",
        "tunisia": "Did you know that in Tunisia, the capital city is Tunis and it has a population of 11,565,204 people?",
        "turkey": "Did you know that in Turkey, the capital city is Ankara and it has a population of 82,319,724 people?",
        "turkmenistan": "Did you know that in Turkmenistan, the capital city is Ashgabat and it has a population of 5,850,908 people?",
        "tuvalu": "Did you know that in Tuvalu, the capital city is Funafuti and it has a population of 11,508 people?",
        "uganda": "Did you know that in Uganda, the capital city is Kampala and it has a population of 42,723,139 people?",
        "ukraine": "Did you know that in Ukraine, the capital city is Kyiv and it has a population of 44,622,516 people?",
        "uae": "Did you know that in UAE, the capital city is Abu Dhabi and it has a population of 9,630,959 people?",
        "uk": "Did you know that in UK, the capital city is London and it has a population of 66,460,344 people?",
        "usa": "Did you know that in USA, the capital city is Washington and it has a population of 326,687,501 people?",
        "uruguay": "Did you know that in Uruguay, the capital city is Montevideo and it has a population of 3,449,299 people?",
        "uzbekistan": "Did you know that in Uzbekistan, the capital city is Toskent and it has a population of 32,955,400 people?",
        "vanuatu": "Did you know that in Vanuatu, the capital city is Port-Vila and it has a population of 292,680 people?",
        "vatican": "Did you know? Vatican City is full of hidden gems waiting to be explored.",
        "venezuela": "Did you know that in Venezuela, the capital city is Caracas and it has a population of 28,870,195 people?",
        "vietnam": "Did you know that in Vietnam, the capital city is Hanoi and it has a population of 95,540,395 people?",
        "yemen": "Did you know that in Yemen, the capital city is Sanaa and it has a population of 28,498,687 people?",
        "zambia": "Did you know that in Zambia, the capital city is Lusaka and it has a population of 17,351,822 people?",
        "zimbabwe": "Did you know that in Zimbabwe, the capital city is Harare and it has a population of 14,439,018 people?",
    };
