import { chromium } from '@playwright/test';
const BASE='http://127.0.0.1:5110';
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:1280,height:900}})).newPage();
await p.goto(`${BASE}/`,{waitUntil:'domcontentloaded'});
await p.evaluate(async()=>{await fetch('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:'test:test-user-1',name:'Alex Rivera'})});localStorage.setItem('gg_auth_token','x');});
await p.evaluate(()=>{ location.hash='#settings'; });
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(1500);
await p.getByText(/General Settings|Paramètres|Configuração|Configuración|Ajustes generais|Definições gerais/i).first().locator('xpath=ancestor::*[self::button or self::a or @role="button"][1]').first().click().catch(async()=>{await p.getByText(/Configure|Configurar|Configurer/i).first().click();});
await p.waitForTimeout(900);
await p.locator('.general-subtab').filter({hasText:/Language|Langue|Idioma/i}).first().click();
await p.waitForTimeout(500);
await p.locator('.theme-option-card').filter({has:p.locator('.theme-option-card__body',{hasText:'English'})}).first().click();
await p.waitForTimeout(1500);
console.log('reset html lang to', await p.evaluate(()=>document.documentElement.lang));
await b.close();
