import { chromium } from '@playwright/test';
const BASE='http://127.0.0.1:5110';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1280,height:900},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto(`${BASE}/`,{waitUntil:'domcontentloaded'});
await p.evaluate(async()=>{await fetch('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:'test:test-user-1',name:'Alex Rivera'})});localStorage.setItem('gg_auth_token','x');});
// reset to EN first via the picker, then reload to make EN the persisted baseline
await p.evaluate(()=>{ location.hash='#settings'; });
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(1500);
await p.getByText(/General Settings|Paramètres généraux/i).first().locator('xpath=ancestor::*[self::button or self::a or @role="button"][1]').first().click().catch(async()=>{await p.getByText(/Configure|Configurer/i).first().click();});
await p.waitForTimeout(900);
await p.locator('.general-subtab').filter({hasText:/Language|Langue|Idioma/i}).first().click();
await p.waitForTimeout(500);
await p.locator('.theme-option-card').filter({has:p.locator('.theme-option-card__body',{hasText:'English'})}).first().click();
await p.waitForTimeout(1500);
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(1500);
// Now baseline is EN. Re-open General > Language
await p.getByText(/General Settings/i).first().locator('xpath=ancestor::*[self::button or self::a or @role="button"][1]').first().click().catch(async()=>{await p.getByText(/Configure/i).first().click();});
await p.waitForTimeout(900);
await p.locator('.general-subtab').filter({hasText:/Language/i}).first().click();
await p.waitForTimeout(500);
const grab=async(label)=>{const d=await p.evaluate(()=>({lang:document.documentElement.lang,subtabs:[...document.querySelectorAll('.general-subtab__label')].map(e=>e.innerText),back:[...document.querySelectorAll('button,a')].map(e=>e.innerText).filter(t=>/Back to|Retour/i.test(t)),title:[...document.querySelectorAll('h1')].map(e=>e.innerText).slice(0,2)}));console.log(label,JSON.stringify(d));};
await grab('EN baseline');
await p.locator('.theme-option-card').filter({has:p.locator('.theme-option-card__body',{hasText:'Français'})}).first().click();
await p.waitForTimeout(500);
await grab('0.5s after EN->FR pick');
await p.waitForTimeout(2000);
await grab('2.5s after EN->FR pick');
await p.screenshot({path:'scratch/audit_mk2/shots/p10_flip_en2fr.png'});
await b.close();
