import { chromium } from '@playwright/test';
const BASE='http://127.0.0.1:5110';
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:1280,height:900}})).newPage();
await p.goto(`${BASE}/`,{waitUntil:'domcontentloaded'});
await p.evaluate(async()=>{await fetch('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:'test:test-user-1',name:'Alex Rivera'})});localStorage.setItem('gg_auth_token','x');});
await p.evaluate(()=>{ location.hash='#settings'; });
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(1500);
await p.getByText(/General Settings|Paramètres|Configuración general|Ajustes generales/i).first().locator('xpath=ancestor::*[self::button or self::a or @role="button"][1]').first().click().catch(async()=>{await p.getByText(/Configure|Configurer|Configurar/i).first().click();});
await p.waitForTimeout(900);
await p.locator('.general-subtab').filter({hasText:/Language|Langue|Idioma/i}).first().click();
await p.waitForTimeout(500);
await p.locator('.theme-option-card').filter({has:p.locator('.theme-option-card__body',{hasText:'Português'})}).first().click();
await p.waitForTimeout(2000);
console.log('html lang', await p.evaluate(()=>document.documentElement.lang));
await p.evaluate(()=>{location.hash='#expenses';}); await p.waitForTimeout(1500);
const txt=await p.evaluate(()=>[...document.querySelectorAll('h1,h2,.nav-item')].map(e=>e.innerText).filter(Boolean).slice(0,8));
console.log('PT page text:', JSON.stringify(txt));
// raw-key leak scan in PT
const leaks=await p.evaluate(()=>{const t=document.body.innerText;const m=t.match(/\b[a-z][a-zA-Z]{2,}\.[a-z][a-zA-Z]{2,}\b/g)||[];return [...new Set(m)].filter(s=>!/\.(com|org|net|js|png|jpg|io|app|html|css|pdf)\b/.test(s)).slice(0,15);});
console.log('PT leaks:', JSON.stringify(leaks));
await b.close();
